// Component exports for easier imports
export { default as Navigation } from './Navigation'
export { default as HeroContent } from './HeroContent'
export { default as HeroSection } from './HeroSection'
export { default as PuzzleGraphics } from './PuzzleGraphics'
export { default as PartnersSection } from './PartnersSection'
export { default as ServicesSection } from './ServicesSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as AnalyticsSection } from './AnalyticsSection'
export { default as FeedbackSection } from './FeedbackSection'
export { default as Footer } from './Footer'
export { default as TosabLogo } from './TosabLogo'

// Data exports
export { heroSections } from '../data/heroData'
export type { HeroData } from '../data/heroData'
export { partners } from '../data/partnersData'
export type { Partner } from '../data/partnersData'
export { services } from '../data/servicesData'
export type { Service } from '../data/servicesData'
export { projects } from '../data/projectsData'
export type { Project } from '../data/projectsData'
export { statistics } from '../data/analyticsData'
export type { Statistic } from '../data/analyticsData'
export { testimonials } from '../data/testimonialsData'
export type { Testimonial } from '../data/testimonialsData'
export { navigationItems } from '../data/navigationData'
export type { NavigationItem, DropdownItem } from '../data/navigationData'
